import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';
import { createEvents } from 'ics';
import OpenAI from "openai";
import { zodResponseFormat } from "openai/helpers/zod";
import { z } from "zod";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const CalendarEvent = z.object({
  title: z.string(),
  start: z.tuple([z.string(), z.string(), z.string(), z.string(), z.string()]),
  end: z.tuple([z.string(), z.string(), z.string(), z.string(), z.string()]),
  description: z.string(),
  url: z.string().optional(),
});

const CalendarEvents = z.array(CalendarEvent);

export async function POST(request) {
  try {
    console.log('Received POST request');
    const formData = await request.formData();
    console.log('FormData created');
    const file = formData.get('file');

    if (!file) {
      console.log('No file uploaded');
      return NextResponse.json({ error: 'No file uploaded' }, { status: 400 });
    }

    console.log('File received:', file.name);
    const buffer = await file.arrayBuffer();
    console.log('File converted to ArrayBuffer');
    const workbook = XLSX.read(new Uint8Array(buffer), { type: 'array' });
    console.log('Workbook read successfully');

    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const jsonData = XLSX.utils.sheet_to_json(worksheet);
    console.log('JSON data extracted:', JSON.stringify(jsonData).slice(0, 100) + '...');

    // Use AI to interpret the data
    console.log('Calling interpretDataWithAI');
    let events;
    try {
      events = await interpretDataWithAI(jsonData);
      console.log('AI interpretation complete. Events:', JSON.stringify(events).slice(0, 100) + '...');
    } catch (aiError) {
      console.error('Error in AI interpretation:', aiError);
      return NextResponse.json({ error: `AI interpretation failed: ${aiError.message}` }, { status: 500 });
    }

    if (!events || events.length === 0) {
      console.error('No events were generated by the AI');
      return NextResponse.json({ error: 'No events were generated' }, { status: 500 });
    }

    console.log('Creating ICS events');
    const { error, value } = createEvents(events);

    if (error) {
      console.error('Error creating ICS events:', error);
      return NextResponse.json({ error: `Failed to create ICS events: ${error}` }, { status: 500 });
    }

    if (!value) {
      console.error('No ICS value generated');
      return NextResponse.json({ error: 'No ICS value generated' }, { status: 500 });
    }

    console.log('ICS events created successfully');
    return new NextResponse(value, {
      status: 200,
      headers: {
        'Content-Type': 'text/calendar',
        'Content-Disposition': 'attachment; filename=calendar.ics',
      },
    });
  } catch (error) {
    console.error('Error processing file:', error);
    return NextResponse.json({ error: `Failed to process the file: ${error.message}` }, { status: 500 });
  }
}

async function interpretDataWithAI(jsonData) {
  console.log('Entering interpretDataWithAI');
  const prompt = `
    You are an AI assistant that interprets Excel data and converts it into calendar events.
    The data represents a schedule of classes or events.
    Please analyze the following JSON data and extract the necessary information to create calendar events.
    Each event should have a title, start date and time, end date and time, description, and URL if available.
    Here's the data:
    ${JSON.stringify(jsonData, null, 2)}
  `;

  console.log('Sending request to OpenAI (GPT-4)');
  try {
    const completion = await openai.beta.chat.completions.parse({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: "Extract the event information from the provided data." },
        { role: "user", content: prompt },
      ],
      response_format: zodResponseFormat(CalendarEvents, "events"),
    });

    const events = completion.choices[0].message.parsed;
    console.log('AI interpreted events:', JSON.stringify(events).slice(0, 100) + '...');
    return events;
  } catch (error) {
    console.error('Error in OpenAI API call:', error);
    throw error;
  }
}
